export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const SYNC_CART_ITEMS = "SYNC_CART_ITEMS";

// Authentication action types
export const CUSTOMER_LOGIN_SUCCESS = "CUSTOMER_LOGIN_SUCCESS";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";
export const CUSTOMER_LOGIN_FAILURE = "CUSTOMER_LOGIN_FAILURE";
export const CUSTOMER_SIGNUP_SUCCESS = "CUSTOMER_SIGNUP_SUCCESS";
export const CUSTOMER_SIGNUP_FAILURE = "CUSTOMER_SIGNUP_FAILURE";
